name = input("what is your name? ")
age = input("what is your age? ")
dateofbirth = input("what is your date of birth? ")
grade = input("what grade are you in? ")

prin("--------------------------")
prin(name)
prin(age)
prin(dateofbirth)
prin(grade)
